### ISSUE TITLE
Question regarding adjustments and device specification while using Bonsai

### ISSUE THREAD

**Issue by AshhadQazi** [open-ephys/OpenEphys.Bonsai.Miniscope#5]
I have successfully managed to get the miniscope working with Bonsai using a file from the Example Workflows folder; however, I am encountering a few issues:

1. I can't find the options to adjust certain parameters such as the camera's focus, which are available in the DAQ software.
2. Bonsai does not seem to offer options to differentiate between types of cameras. In the DAQ software, different device IDs specify whether the camera is a miniscope or webcam, but I do not see this distinction in Bonsai.
![Capture](https://github.com/open-ephys/OpenEphys.Bonsai.Miniscope/assets/170653199/4d52e2f9-2139-4680-b3fc-1351d724cbb0)

Could you please provide guidance of suggestions to address these issues? Thank you!

**Comment by jonnew** [comment]
- All miniscopes present themselves as a standard webcam in terms of their USB descriptor. To figure out if they are a e.g. a webcam from logitech versus a UCLA minscope probably requires opening the device and examining metadata. Of course there a ways to do this but right now we don't plan to support it. 
- "EWL" is the electrowetting lens focus, move the slider around to adjust the focus
- "FramesPerSecond" provides a set of video rates to choose from

@cjsha is working on our [miniscope docs](https://open-ephys.github.io/miniscope-docs/index.html). It will have a section for using the Bonsai library. @cjsha make sure you address these concerns in the docs.

**Comment by jonnew** [comment]
@AshhadQazi  I'm looking at old versions of this issue, which i have in my email. Can you confirm that you issues with the LED, frame rate, etc, were actually non-issues?

**Comment by cjsha** [comment]
Hi @AshhadQazi. Since this issue is more pertinent to the [miniscope-docs repo](https://github.com/open-ephys/miniscope-docs/issues/12), I'll address it there. This repo is more for questions or edits regarding the Bonsai package that underlies the UclaMiniscopeV4 node.
