### ISSUE TITLE
Default FMP4 encoder is too lossey for downstream pipelines

### ISSUE THREAD

**Issue by dprotter** [open-ephys/OpenEphys.Bonsai.Miniscope#8]
I and some other researchers have been recording miniscope data for a few weeks, and noticed when we began pre-processing data that we have unusual artifacts from the default FMP4 encoder. These appear as a grid of highly correlated pixels, and disrupt downstream data analysis. An example from caiman is below.

![image](https://github.com/open-ephys/OpenEphys.Bonsai.Miniscope/assets/12704406/989117fd-97a1-402a-a659-8f46c19fa90b)

![image](https://github.com/open-ephys/OpenEphys.Bonsai.Miniscope/assets/12704406/65cafad4-a904-41ca-a3c9-e389649fd503)

HFYU works in bonsai seems to introduce far fewer artifacts:

![image](https://github.com/open-ephys/OpenEphys.Bonsai.Miniscope/assets/12704406/5265075d-02ef-4d02-900d-77f2ac042db3)

![image](https://github.com/open-ephys/OpenEphys.Bonsai.Miniscope/assets/12704406/76ddff12-9372-400e-837d-db9ce6fcdf02)

I propose having the default encoder be either a lossless encoder like "HFYU" or a raw encoder like "DIB ".

**Comment by jonnew** [comment]
I'm going to be honest, most of these don't look like cells but potentially autofluorescent blood vessels or some other artifact, in both scenarios.

Regardless, it is disturbing that the encoder does affect the results so much, whether the data is valid to begin with or not. I guess we should probably just default to no compression.

**Comment by ChucklesOnGitHub** [comment]
We were looking at encoding data in the same way the Miniscope-DAQ-qt software does a while back with @mgraupe using the FFMPeg VideoWriter node. To use the 8 bit gray format the Miniscope-DAQ-QT software does he used the command “-c: ffv1 -pix_fmt gray -bits_per_raw_sample 8”. We then found that FFMPeg running in the background was quite slow for long videos and that sometimes it would cause the task programmed in Bonsai to go indefinitely and then the resulting video files were corrupted. I would be keen on having a default recommendation to write miniscope data to file.

**Comment by dprotter** [comment]
@jonnew the cell-shaped stuff on the right image are definitely cells. High SNR, dont even need df/f to see most of them.The longer bands in the correlation image seem to be encoder artifacts. 

![image](https://github.com/user-attachments/assets/13460cf6-679c-428f-ab63-8b94026fd8be)

rather than defaulting to "DIB " (uncompressed, I believe?) I think HFYU or getting instructions on troubleshooting FFMPEG to work for FFV1 would be more appropriate. the uncompressed files are just too large to realistically work with for people who do longitudinal imaging, in my opinion.

**Comment by jonnew** [comment]
Hi David, I'm not sure I agree with you. Can you image with uncompressed so we can take a look at those correlated areas? The degree of correlation might change a bit, which, again, is worrying, but they are not just going to turn into cells.

Assuming this is the case, the main issue is the signal itself. 

Where are you imaging?
